services:
  stockfish:
    image: ivangabriele/stockfish:15
    container_name: stockfish_container
    environment:
      - API_TOKEN=PASS
      - DOMAIN=*
      - PORT=4000
    ports:
      - '4000:4000'
